version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ApiRamadaDev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n0l2myodwcao"
s3_prefix = "ApiRamadaDev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[Prod]
stack_name = "ApiRamadaProd"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n0l2myodwcao"
s3_prefix = "ApiRamadaProd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []